spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.102.1:3306/viajes?serverTimezone=UTC
    username: user
    password: passwordMicro2021   
  jpa:
    hibernate:
      naming.implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  application:
    name: servicio-reservas
server:
  port: 8082
  error:
    include-message: always
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.102.1:8761/eureka
